// Theme categories
export const themeCategories = [
  { id: "modern", name: "Modern" },
  { id: "minimal", name: "Minimal" },
  { id: "gaming", name: "Gaming" },
  { id: "corporate", name: "Corporate" },
  { id: "creative", name: "Creative" },
  { id: "monochrome", name: "Monochrome" },
  { id: "vibrant", name: "Vibrant" },
  { id: "unique", name: "Unique" },
];

// Helper function to convert hex to HSL
function hexToHSL(hex: string): string {
  // Remove the # if present
  hex = hex.replace(/^#/, "");

  // Parse the hex values
  const r = Number.parseInt(hex.substring(0, 2), 16) / 255;
  const g = Number.parseInt(hex.substring(2, 4), 16) / 255;
  const b = Number.parseInt(hex.substring(4, 6), 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);

    switch (max) {
      case r:
        h = (g - b) / d + (g < b ? 6 : 0);
        break;
      case g:
        h = (b - r) / d + 2;
        break;
      case b:
        h = (r - g) / d + 4;
        break;
    }
    h /= 6;
  }

  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

// Helper function to lighten a color
function lightenColor(hex: string, amount = 20): string {
  // Remove the # if present
  hex = hex.replace(/^#/, "");

  // Parse the hex values
  const r = Number.parseInt(hex.substring(0, 2), 16);
  const g = Number.parseInt(hex.substring(2, 4), 16);
  const b = Number.parseInt(hex.substring(4, 6), 16);

  // Lighten each component
  const newR = Math.min(255, r + amount);
  const newG = Math.min(255, g + amount);
  const newB = Math.min(255, b + amount);

  // Convert back to hex
  return `#${newR.toString(16).padStart(2, "0")}${newG.toString(16).padStart(2, "0")}${newB.toString(16).padStart(2, "0")}`;
}

// Helper function to generate chart colors based on primary color
function generateChartColors(primaryColor: string): Record<string, string> {
  const primaryHSL = hexToHSL(primaryColor);
  const [h, s, l] = primaryHSL.split(" ").map((val, i) => {
    if (i === 0) return Number.parseInt(val);
    return Number.parseInt(val.replace("%", ""));
  });

  // Generate 6 chart colors based on primary color
  const chartColors = {
    "chart-1": hexToHSL(primaryColor), // Primary color
    "chart-2": `${(h + 60) % 360} ${Math.max(50, s)}% ${Math.min(70, l + 10)}%`, // Complementary
    "chart-3": `${(h + 120) % 360} ${Math.max(45, s - 10)}% ${Math.min(65, l + 5)}%`, // Triadic
    "chart-4": `${(h + 180) % 360} ${Math.max(55, s + 5)}% ${Math.min(75, l + 15)}%`, // Opposite
    "chart-5": `${(h + 240) % 360} ${Math.max(50, s)}% ${Math.min(70, l + 10)}%`, // Split complementary
    "chart-6": `${(h + 300) % 360} ${Math.max(45, s - 5)}% ${Math.min(65, l + 5)}%`, // Split complementary 2
  };

  return chartColors;
}

// Helper function to generate CSS variables from theme colors
function generateCSSVariables(colors: Record<string, string>): {
  light: Record<string, string>;
  dark: Record<string, string>;
} {
  // Generate chart colors based on primary color
  const chartColors = generateChartColors(colors.primary || "#0070f3");

  // Helper function to darken a color for dark mode
  function darkenForDarkMode(hex: string, amount = 30): string {
    const hsl = hexToHSL(hex);
    const [h, s, l] = hsl.split(" ").map((val, i) => {
      if (i === 0) return Number.parseInt(val);
      return Number.parseInt(val.replace("%", ""));
    });

    const newL = Math.max(10, l - amount);
    return `${h} ${s}% ${newL}%`;
  }

  // Helper function to lighten a color for dark mode text
  function lightenForDarkMode(hex: string, amount = 40): string {
    const hsl = hexToHSL(hex);
    const [h, s, l] = hsl.split(" ").map((val, i) => {
      if (i === 0) return Number.parseInt(val);
      return Number.parseInt(val.replace("%", ""));
    });

    // If the color is very dark (lightness < 20%), use white or very light color
    if (l < 20) {
      return "0 0% 98%"; // Almost white
    }

    // If the color is already light (lightness > 70%), darken it instead
    if (l > 70) {
      const newL = Math.max(20, l - amount);
      return `${h} ${s}% ${newL}%`;
    }

    // For medium colors, lighten them
    const newL = Math.min(90, l + amount);
    return `${h} ${s}% ${newL}%`;
  }

  const light = {
    background: hexToHSL(colors.background || "#ffffff"),
    foreground: "0 0% 3.9%",
    card: hexToHSL(colors.background || "#ffffff"),
    "card-foreground": "0 0% 3.9%",
    popover: hexToHSL(colors.background || "#ffffff"),
    "popover-foreground": "0 0% 3.9%",
    primary: hexToHSL(colors.primary || "#000000"),
    "primary-foreground": "0 0% 98%",
    secondary: hexToHSL(colors.secondary || "#f1f5f9"),
    "secondary-foreground": "0 0% 9%",
    tertiary: "240 8% 95%",
    "tertiary-foreground": "240 8% 20%",
    neutral: "240 5% 90%",
    "neutral-foreground": "240 5% 15%",
    muted: hexToHSL(colors.muted || "#f1f5f9"),
    "muted-foreground": "0 0% 45.1%",
    accent: hexToHSL(colors.accent || "#f1f5f9"),
    "accent-foreground": "0 0% 9%",
    destructive: hexToHSL(colors.destructive || "#ef4444"),
    "destructive-foreground": "0 0% 100%",
    border: hexToHSL(colors.border || "#e2e8f0"),
    input: hexToHSL(colors.border || "#e2e8f0"),
    ring: hexToHSL(colors.primary || "#000000"),
    shadow: "0 10px 50px rgba(0, 0, 0, 0.1)",
    "gradient-start": "220 50% 40%",
    "gradient-end": "280 40% 30%",
    ...chartColors, // Use generated chart colors
    radius: "0.5rem",
  };

  const dark = {
    background: "240 10% 3.9%",
    foreground: "0 0% 98%",
    card: "240 10% 3.9%",
    "card-foreground": "0 0% 98%",
    popover: "240 10% 3.9%",
    "popover-foreground": "0 0% 98%",
    primary: lightenForDarkMode(colors.primary || "#000000"),
    "primary-foreground": "240 5.9% 10%",
    secondary: "240 3.7% 15.9%",
    "secondary-foreground": "0 0% 98%",
    tertiary: "240 8% 15%",
    "tertiary-foreground": "240 8% 80%",
    neutral: "240 5% 20%",
    "neutral-foreground": "240 5% 85%",
    muted: "240 3.7% 15.9%",
    "muted-foreground": "240 5% 64.9%",
    accent: darkenForDarkMode(colors.accent || "#f1f5f9", 60),
    "accent-foreground": "0 0% 98%",
    destructive: "0 62.8% 30.6%",
    "destructive-foreground": "0 0% 98%",
    border: "240 3.7% 15.9%",
    input: "240 3.7% 15.9%",
    ring: lightenForDarkMode(colors.primary || "#000000"),
    // Use adapted chart colors for dark mode
    "chart-1": lightenForDarkMode(colors.primary || "#0070f3"),
    "chart-2": chartColors["chart-2"],
    "chart-3": chartColors["chart-3"],
    "chart-4": chartColors["chart-4"],
    "chart-5": chartColors["chart-5"],
    "chart-6": chartColors["chart-6"],
  };

  return { light, dark };
}

// Preset themes with lighter accent colors
export const presetThemes = [
  {
    id: "default-shadcn",
    name: "Default",
    category: ["minimal"],
    colors: {
      background: "#ffffff",
      primary: "#0f172a",
      secondary: "#f1f5f9",
      accent: "#f8fafc",
      destructive: "#ef4444",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Geist",
      textFont: "Geist",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "sm",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#0f172a",
      secondary: "#f1f5f9",
      accent: "#f8fafc",
      destructive: "#ef4444",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "business-blue",
    name: "Business Blue",
    category: ["corporate", "minimal"],
    colors: {
      background: "#ffffff",
      primary: "#1a56db",
      secondary: "#f7fafc",
      accent: "#dbeafe",
      destructive: "#e02424",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Montserrat",
      textFont: "Open Sans",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "sm",
      animationSpeed: 300,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#1a56db",
      secondary: "#f7fafc",
      accent: "#dbeafe",
      destructive: "#e02424",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "creative-purple",
    name: "Creative Purple",
    category: ["creative", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#8b5cf6",
      secondary: "#f5f3ff",
      accent: "#e9d5ff",
      destructive: "#ef4444",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Playfair Display",
      textFont: "Raleway",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "lg",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#8b5cf6",
      secondary: "#f5f3ff",
      accent: "#e9d5ff",
      destructive: "#ef4444",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "ocean-blue",
    name: "Ocean Blue",
    category: ["unique", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#0ea5e9",
      secondary: "#f0f9ff",
      accent: "#bae6fd",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Montserrat",
      textFont: "Lato",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "md",
      animationSpeed: 250,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#0ea5e9",
      secondary: "#f0f9ff",
      accent: "#bae6fd",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "forest-green",
    name: "Forest Green",
    category: ["unique", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#16a34a",
      secondary: "#f0fdf4",
      accent: "#bbf7d0",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Poppins",
      textFont: "Source Sans Pro",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "md",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#16a34a",
      secondary: "#f0fdf4",
      accent: "#bbf7d0",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "sunset-orange",
    name: "Sunset Orange",
    category: ["creative", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#f97316",
      secondary: "#fff7ed",
      accent: "#fed7aa",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Nunito",
      textFont: "Nunito",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "lg",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#f97316",
      secondary: "#fff7ed",
      accent: "#fed7aa",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "rose-pink",
    name: "Rose Pink",
    category: ["creative", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#ec4899",
      secondary: "#fdf2f8",
      accent: "#fbcfe8",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Quicksand",
      textFont: "Quicksand",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "md",
      animationSpeed: 250,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#ec4899",
      secondary: "#fdf2f8",
      accent: "#fbcfe8",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "golden-yellow",
    name: "Golden Yellow",
    category: ["unique", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#eab308",
      secondary: "#fefce8",
      accent: "#fef3c7",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Comfortaa",
      textFont: "Comfortaa",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "md",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#eab308",
      secondary: "#fefce8",
      accent: "#fef3c7",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "teal-mint",
    name: "Teal Mint",
    category: ["unique", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#14b8a6",
      secondary: "#f0fdfa",
      accent: "#99f6e4",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Raleway",
      textFont: "Lato",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "md",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#14b8a6",
      secondary: "#f0fdfa",
      accent: "#99f6e4",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "indigo-deep",
    name: "Indigo Deep",
    category: ["corporate", "minimal"],
    colors: {
      background: "#ffffff",
      primary: "#6366f1",
      secondary: "#f8fafc",
      accent: "#c7d2fe",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Work Sans",
      textFont: "Work Sans",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "sm",
      animationSpeed: 300,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#6366f1",
      secondary: "#f8fafc",
      accent: "#c7d2fe",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  // Continue with remaining themes with lighter accent colors...
  {
    id: "coral-red",
    name: "Coral Red",
    category: ["creative", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#ef4444",
      secondary: "#fef2f2",
      accent: "#fecaca",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Rubik",
      textFont: "Rubik",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "md",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#ef4444",
      secondary: "#fef2f2",
      accent: "#fecaca",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "slate-gray",
    name: "Slate Gray",
    category: ["corporate", "minimal"],
    colors: {
      background: "#ffffff",
      primary: "#64748b",
      secondary: "#f8fafc",
      accent: "#e2e8f0",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "IBM Plex Sans",
      textFont: "IBM Plex Sans",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.125rem",
      shadow: "sm",
      animationSpeed: 300,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#64748b",
      secondary: "#f8fafc",
      accent: "#e2e8f0",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "emerald-fresh",
    name: "Emerald Fresh",
    category: ["unique", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#10b981",
      secondary: "#ecfdf5",
      accent: "#a7f3d0",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Manrope",
      textFont: "Manrope",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "md",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#10b981",
      secondary: "#ecfdf5",
      accent: "#a7f3d0",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "violet-dream",
    name: "Violet Dream",
    category: ["creative", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#7c3aed",
      secondary: "#f5f3ff",
      accent: "#ddd6fe",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Josefin Sans",
      textFont: "Josefin Sans",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "lg",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#7c3aed",
      secondary: "#f5f3ff",
      accent: "#ddd6fe",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "amber-warm",
    name: "Amber Warm",
    category: ["unique", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#f59e0b",
      secondary: "#fffbeb",
      accent: "#fde68a",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "DM Sans",
      textFont: "DM Sans",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "md",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#f59e0b",
      secondary: "#fffbeb",
      accent: "#fde68a",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "cyber-neon",
    name: "Cyber Neon",
    category: ["gaming", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#00ff88",
      secondary: "#f0fff4",
      accent: "#ccfbf1",
      destructive: "#ff0066",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Orbitron",
      textFont: "Exo 2",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.125rem",
      shadow: "lg",
      animationSpeed: 150,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#00ff88",
      secondary: "#f0fff4",
      accent: "#ccfbf1",
      destructive: "#ff0066",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "royal-purple",
    name: "Royal Purple",
    category: ["creative", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#9333ea",
      secondary: "#faf5ff",
      accent: "#e9d5ff",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Cinzel",
      textFont: "Lora",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "xl",
      animationSpeed: 250,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#9333ea",
      secondary: "#faf5ff",
      accent: "#e9d5ff",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "mint-fresh",
    name: "Mint Fresh",
    category: ["unique", "minimal"],
    colors: {
      background: "#ffffff",
      primary: "#06d6a0",
      secondary: "#f0fdfa",
      accent: "#a7f3d0",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Nunito Sans",
      textFont: "Nunito Sans",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "md",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#06d6a0",
      secondary: "#f0fdfa",
      accent: "#a7f3d0",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "crimson-fire",
    name: "Crimson Fire",
    category: ["creative", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#dc143c",
      secondary: "#fef2f2",
      accent: "#fecaca",
      destructive: "#b91c1c",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Oswald",
      textFont: "Roboto",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.25rem",
      shadow: "lg",
      animationSpeed: 180,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#dc143c",
      secondary: "#fef2f2",
      accent: "#fecaca",
      destructive: "#b91c1c",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "sapphire-blue",
    name: "Sapphire Blue",
    category: ["corporate", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#0f52ba",
      secondary: "#eff6ff",
      accent: "#bfdbfe",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Merriweather",
      textFont: "Open Sans",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "md",
      animationSpeed: 220,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#0f52ba",
      secondary: "#eff6ff",
      accent: "#bfdbfe",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "midnight-blue",
    name: "Midnight Blue",
    category: ["corporate", "minimal"],
    colors: {
      background: "#ffffff",
      primary: "#1e3a8a",
      secondary: "#f1f5f9",
      accent: "#dbeafe",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Inter",
      textFont: "Inter",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "sm",
      animationSpeed: 300,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#1e3a8a",
      secondary: "#f1f5f9",
      accent: "#dbeafe",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "cherry-blossom",
    name: "Cherry Blossom",
    category: ["creative", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#f472b6",
      secondary: "#fdf2f8",
      accent: "#fce7f3",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Poppins",
      textFont: "Poppins",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "md",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#f472b6",
      secondary: "#fdf2f8",
      accent: "#fce7f3",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "arctic-frost",
    name: "Arctic Frost",
    category: ["minimal", "monochrome"],
    colors: {
      background: "#ffffff",
      primary: "#475569",
      secondary: "#f8fafc",
      accent: "#f1f5f9",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Roboto",
      textFont: "Roboto",
      displayWeight: 500,
      textWeight: 400,
    },
    styles: {
      radius: "0.25rem",
      shadow: "sm",
      animationSpeed: 350,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#475569",
      secondary: "#f8fafc",
      accent: "#f1f5f9",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "neon-lime",
    name: "Neon Lime",
    category: ["gaming", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#84cc16",
      secondary: "#f7fee7",
      accent: "#d9f99d",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Exo 2",
      textFont: "Exo 2",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.125rem",
      shadow: "lg",
      animationSpeed: 150,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#84cc16",
      secondary: "#f7fee7",
      accent: "#d9f99d",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "coffee-brown",
    name: "Coffee Brown",
    category: ["unique", "minimal"],
    colors: {
      background: "#ffffff",
      primary: "#92400e",
      secondary: "#fef3c7",
      accent: "#fde68a",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Merriweather",
      textFont: "Source Sans Pro",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "md",
      animationSpeed: 250,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#92400e",
      secondary: "#fef3c7",
      accent: "#fde68a",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "electric-blue",
    name: "Electric Blue",
    category: ["gaming", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#0ea5e9",
      secondary: "#f0f9ff",
      accent: "#bae6fd",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Orbitron",
      textFont: "Roboto",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.25rem",
      shadow: "xl",
      animationSpeed: 180,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#0ea5e9",
      secondary: "#f0f9ff",
      accent: "#bae6fd",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "lavender-mist",
    name: "Lavender Mist",
    category: ["creative", "minimal"],
    colors: {
      background: "#ffffff",
      primary: "#a855f7",
      secondary: "#faf5ff",
      accent: "#e9d5ff",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Playfair Display",
      textFont: "Lato",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "md",
      animationSpeed: 220,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#a855f7",
      secondary: "#faf5ff",
      accent: "#e9d5ff",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "charcoal-dark",
    name: "Charcoal Dark",
    category: ["monochrome", "corporate"],
    colors: {
      background: "#ffffff",
      primary: "#374151",
      secondary: "#f9fafb",
      accent: "#f3f4f6",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "IBM Plex Sans",
      textFont: "IBM Plex Sans",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.125rem",
      shadow: "sm",
      animationSpeed: 300,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#374151",
      secondary: "#f9fafb",
      accent: "#f3f4f6",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "sunset-peach",
    name: "Sunset Peach",
    category: ["creative", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#fb923c",
      secondary: "#fff7ed",
      accent: "#fed7aa",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Quicksand",
      textFont: "Nunito",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "lg",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#fb923c",
      secondary: "#fff7ed",
      accent: "#fed7aa",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "steel-gray",
    name: "Steel Gray",
    category: ["corporate", "monochrome"],
    colors: {
      background: "#ffffff",
      primary: "#6b7280",
      secondary: "#f9fafb",
      accent: "#f3f4f6",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Work Sans",
      textFont: "Work Sans",
      displayWeight: 500,
      textWeight: 400,
    },
    styles: {
      radius: "0.25rem",
      shadow: "sm",
      animationSpeed: 300,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#6b7280",
      secondary: "#f9fafb",
      accent: "#f3f4f6",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "tropical-cyan",
    name: "Tropical Cyan",
    category: ["unique", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#06b6d4",
      secondary: "#ecfeff",
      accent: "#a5f3fc",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Raleway",
      textFont: "Open Sans",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "md",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#06b6d4",
      secondary: "#ecfeff",
      accent: "#a5f3fc",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "magenta-pop",
    name: "Magenta Pop",
    category: ["creative", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#d946ef",
      secondary: "#fdf4ff",
      accent: "#f5d0fe",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Comfortaa",
      textFont: "Nunito Sans",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "lg",
      animationSpeed: 180,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#d946ef",
      secondary: "#fdf4ff",
      accent: "#f5d0fe",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "bronze-copper",
    name: "Bronze Copper",
    category: ["unique", "minimal"],
    colors: {
      background: "#ffffff",
      primary: "#c2410c",
      secondary: "#fff7ed",
      accent: "#fed7aa",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Cinzel",
      textFont: "Lora",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "md",
      animationSpeed: 250,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#c2410c",
      secondary: "#fff7ed",
      accent: "#fed7aa",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "neon-pink",
    name: "Neon Pink",
    category: ["gaming", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#ff0080",
      secondary: "#fdf2f8",
      accent: "#fce7f3",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Orbitron",
      textFont: "Exo 2",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.125rem",
      shadow: "xl",
      animationSpeed: 150,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#ff0080",
      secondary: "#fdf2f8",
      accent: "#fce7f3",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "sage-green",
    name: "Sage Green",
    category: ["minimal", "unique"],
    colors: {
      background: "#ffffff",
      primary: "#84cc16",
      secondary: "#f7fee7",
      accent: "#d9f99d",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Manrope",
      textFont: "Inter",
      displayWeight: 500,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "sm",
      animationSpeed: 250,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#84cc16",
      secondary: "#f7fee7",
      accent: "#d9f99d",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  // Modern Themes (5)
  {
    id: "modern-gradient",
    name: "Modern Gradient",
    category: ["modern", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#6366f1",
      secondary: "#f8fafc",
      accent: "#e0e7ff",
      destructive: "#ef4444",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Inter",
      textFont: "Inter",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.75rem",
      shadow: "xl",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#6366f1",
      secondary: "#f8fafc",
      accent: "#e0e7ff",
      destructive: "#ef4444",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "modern-glass",
    name: "Modern Glass",
    category: ["modern", "minimal"],
    colors: {
      background: "#ffffff",
      primary: "#0f172a",
      secondary: "#f8fafc",
      accent: "#f1f5f9",
      destructive: "#ef4444",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Poppins",
      textFont: "Poppins",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "1rem",
      shadow: "2xl",
      animationSpeed: 250,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#0f172a",
      secondary: "#f8fafc",
      accent: "#f1f5f9",
      destructive: "#ef4444",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "modern-neon",
    name: "Modern Neon",
    category: ["modern", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#8b5cf6",
      secondary: "#faf5ff",
      accent: "#e9d5ff",
      destructive: "#ef4444",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Space Grotesk",
      textFont: "Space Grotesk",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "lg",
      animationSpeed: 180,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#8b5cf6",
      secondary: "#faf5ff",
      accent: "#e9d5ff",
      destructive: "#ef4444",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "modern-tech",
    name: "Modern Tech",
    category: ["modern", "corporate"],
    colors: {
      background: "#ffffff",
      primary: "#0ea5e9",
      secondary: "#f0f9ff",
      accent: "#bae6fd",
      destructive: "#ef4444",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "JetBrains Mono",
      textFont: "Inter",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.25rem",
      shadow: "md",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#0ea5e9",
      secondary: "#f0f9ff",
      accent: "#bae6fd",
      destructive: "#ef4444",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "modern-aurora",
    name: "Modern Aurora",
    category: ["modern", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#ec4899",
      secondary: "#fdf2f8",
      accent: "#fbcfe8",
      destructive: "#ef4444",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Outfit",
      textFont: "Outfit",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.75rem",
      shadow: "xl",
      animationSpeed: 200,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#ec4899",
      secondary: "#fdf2f8",
      accent: "#fbcfe8",
      destructive: "#ef4444",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },

  // Elegant Themes (5)
  {
    id: "elegant-gold",
    name: "Elegant Gold",
    category: ["creative", "unique"],
    colors: {
      background: "#ffffff",
      primary: "#d97706",
      secondary: "#fffbeb",
      accent: "#fde68a",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Playfair Display",
      textFont: "Cormorant Garamond",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "lg",
      animationSpeed: 300,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#d97706",
      secondary: "#fffbeb",
      accent: "#fde68a",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "elegant-navy",
    name: "Elegant Navy",
    category: ["corporate", "minimal"],
    colors: {
      background: "#ffffff",
      primary: "#1e40af",
      secondary: "#eff6ff",
      accent: "#dbeafe",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Crimson Text",
      textFont: "Libre Baskerville",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "md",
      animationSpeed: 350,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#1e40af",
      secondary: "#eff6ff",
      accent: "#dbeafe",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "elegant-burgundy",
    name: "Elegant Burgundy",
    category: ["creative", "unique"],
    colors: {
      background: "#ffffff",
      primary: "#991b1b",
      secondary: "#fef2f2",
      accent: "#fecaca",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Cormorant Garamond",
      textFont: "Crimson Text",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.5rem",
      shadow: "lg",
      animationSpeed: 300,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#991b1b",
      secondary: "#fef2f2",
      accent: "#fecaca",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "elegant-emerald",
    name: "Elegant Emerald",
    category: ["unique", "minimal"],
    colors: {
      background: "#ffffff",
      primary: "#059669",
      secondary: "#ecfdf5",
      accent: "#a7f3d0",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Libre Baskerville",
      textFont: "Playfair Display",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.375rem",
      shadow: "md",
      animationSpeed: 300,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#059669",
      secondary: "#ecfdf5",
      accent: "#a7f3d0",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "elegant-platinum",
    name: "Elegant Platinum",
    category: ["minimal", "monochrome"],
    colors: {
      background: "#ffffff",
      primary: "#4b5563",
      secondary: "#f9fafb",
      accent: "#f3f4f6",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Cormorant Garamond",
      textFont: "Source Serif Pro",
      displayWeight: 600,
      textWeight: 400,
    },
    styles: {
      radius: "0.25rem",
      shadow: "sm",
      animationSpeed: 350,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#4b5563",
      secondary: "#f9fafb",
      accent: "#f3f4f6",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },

  // Comic Themes (4)
  {
    id: "comic-pop",
    name: "Comic Pop",
    category: ["creative", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#ff6b35",
      secondary: "#fff7ed",
      accent: "#fed7aa",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Fredoka One",
      textFont: "Comic Neue",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "1rem",
      shadow: "xl",
      animationSpeed: 150,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#ff6b35",
      secondary: "#fff7ed",
      accent: "#fed7aa",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "comic-bubble",
    name: "Comic Bubble",
    category: ["creative", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#3b82f6",
      secondary: "#eff6ff",
      accent: "#bfdbfe",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Bangers",
      textFont: "Fredoka One",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "1.5rem",
      shadow: "2xl",
      animationSpeed: 120,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#3b82f6",
      secondary: "#eff6ff",
      accent: "#bfdbfe",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "comic-hero",
    name: "Comic Hero",
    category: ["creative", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#dc2626",
      secondary: "#fef2f2",
      accent: "#fecaca",
      destructive: "#b91c1c",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Bungee",
      textFont: "Bangers",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "0.75rem",
      shadow: "xl",
      animationSpeed: 100,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#dc2626",
      secondary: "#fef2f2",
      accent: "#fecaca",
      destructive: "#b91c1c",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
  {
    id: "comic-rainbow",
    name: "Comic Rainbow",
    category: ["creative", "vibrant"],
    colors: {
      background: "#ffffff",
      primary: "#a855f7",
      secondary: "#faf5ff",
      accent: "#e9d5ff",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    },
    fonts: {
      displayFont: "Righteous",
      textFont: "Comic Neue",
      displayWeight: 700,
      textWeight: 400,
    },
    styles: {
      radius: "1rem",
      shadow: "2xl",
      animationSpeed: 150,
      fadeSpeed: 500,
      scaleSpeed: 300,
      slideSpeed: 500,
      marqueeSpeed: 20,
      shineSpeed: 8,
      animationCurve: "ease",
    },
    cssVariables: generateCSSVariables({
      background: "#ffffff",
      primary: "#a855f7",
      secondary: "#faf5ff",
      accent: "#e9d5ff",
      destructive: "#dc2626",
      muted: "#f1f5f9",
      border: "#e2e8f0",
    }),
  },
];
